# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='分多少发呆', max_length=15, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='用户手机号'),
        ),
    ]
