# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190103_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'comment',
                'db_table': 'tb_comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='文章内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Article', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='son_comments', to='users.Comment', verbose_name='父评论'),
        ),
    ]
