# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='focus_url',
            field=models.ImageField(null=True, upload_to='', verbose_name='缩略图'),
        ),
    ]
