# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_article_focus_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='trans_count',
            field=models.IntegerField(default=0, verbose_name='转发数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500, null=True, verbose_name='评论内容'),
        ),
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='collect_articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Article', verbose_name='收藏文臧'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_users', to='users.Article', verbose_name='点赞文章'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_users', to='users.Comment', verbose_name='点赞评论'),
        ),
    ]
