# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190104_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_articles',
        ),
        migrations.AddField(
            model_name='user',
            name='like_articles',
            field=models.ManyToManyField(null=True, related_name='like_users', to='users.Article', verbose_name='点赞文章'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_comments',
        ),
        migrations.AddField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(null=True, related_name='like_users', to='users.Comment', verbose_name='点赞评论'),
        ),
    ]
